version: "0.0.1"
services:
  hyperdiffusion:
    shm_size: 24gb
    container_name: hyperdiffusion
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vols/data:/hyperdiffusion/data
      - ./vols/checkpoints:/hyperdiffusion/checkpoints
      - ./vols/output_files:/hyperdiffusion/output_files
      - ./vols/mlp_weights:/hyperdiffusion/mlp_weights
      - ./vols/gen_meshes:/hyperdiffusion/gen_meshes
      - ./src/configs:/hyperdiffusion/configs
      - ./src/vae:/hyperdiffusion/vae
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - CONDA_DIR=/opt/conda
    env_file:
      - .env
